version: '3'
services:
  db:
    image: quovadis1212/cookbook-db
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_DATABASE: RecipeCache

  app:
    image: quovadis1212/cookbook-companion
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=CHANGEME
      - DATABASE_DB=RecipeCache
